#!/usr/bin/env python3
"""Convert the members' survey export (.xlsx) into _data/people.yml.

The Google Form export is the upstream source of truth; _data/people.yml is
what the site actually renders. Re-run this after a new export, then read the
diff before committing -- hand edits made directly to the YAML will be
overwritten, so fold them back into the form or into this script.

    python3 tools/import_people.py ~/Downloads/<survey export>.xlsx

Expected columns (Google Forms question order):
    A timestamp   B name(ko)    C name(en)   D affiliation(ko) E affiliation(en)
    F field(ko)   G field(en)   H email      I photo(drive)    J bio(ko)
    K bio(en)     L link        M past presentation titles

Column I holds Google Drive links that require sign-in, so photos are not
imported; the site is text-only. Column M duplicates what is already recorded
in _seminar/, so it is skipped too.
"""

import re
import sys
import zipfile
from xml.etree import ElementTree as ET

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
M = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"

FIELDS = [
    ("name", "B"),
    ("name_en", "C"),
    ("affiliation", "D"),
    ("affiliation_en", "E"),
    ("field", "F"),
    ("field_en", "G"),
    ("email", "H"),
    ("bio", "J"),
    ("bio_en", "K"),
    ("link", "L"),
]

# Personal links show as a platform name rather than a raw URL. Anything not
# recognised falls back to its bare domain, which reads the same in KO and EN.
PLATFORMS = [
    ("linkedin.com", "LinkedIn"),
    ("notion.site", "Notion"),
    ("notion.so", "Notion"),
    ("github.com", "GitHub"),
    ("instagram.com", "Instagram"),
    ("x.com", "X"),
    ("twitter.com", "X"),
    ("orcid.org", "ORCID"),
    ("scholar.google", "Google Scholar"),
    ("academia.edu", "Academia.edu"),
    ("researchgate.net", "ResearchGate"),
    ("brunch.co.kr", "brunch"),
    ("tistory.com", "Tistory"),
    ("velog.io", "velog"),
]


def link_label(url):
    """A human label for a personal link: platform name, else the bare domain."""
    host = re.sub(r"^https?://", "", url).split("/")[0].lower()
    for needle, label in PLATFORMS:
        if needle in host:
            return label
    return re.sub(r"^www\.", "", host)

HEADER = """# Members, generated by tools/import_people.py from the survey export.
# Rendered by people.html. Re-run the importer rather than editing by hand.
"""


def read_rows(path):
    """Return the sheet as a list of {column letter: value} dicts, minus the header."""
    z = zipfile.ZipFile(path)
    shared = [
        "".join(t.text or "" for t in si.iter(M + "t"))
        for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall("m:si", NS)
    ]

    rows = {}
    for row in ET.fromstring(z.read("xl/worksheets/sheet1.xml")).iter(M + "row"):
        cells = {}
        for c in row.findall("m:c", NS):
            v = c.find("m:v", NS)
            if v is None or v.text is None:
                continue
            value = shared[int(v.text)] if c.get("t") == "s" else v.text
            cells[re.sub(r"\d+$", "", c.get("r"))] = value
        rows[int(row.get("r"))] = cells

    return [rows[i] for i in sorted(rows) if i >= 2]


def clean(value):
    """Normalise a cell: strip stray whitespace, drop zero-width junk from pasted text."""
    if not value:
        return ""
    value = value.replace("\r\n", "\n").replace("​", "").replace("\xa0", " ")
    return "\n".join(line.strip() for line in value.split("\n")).strip("\n ")


def emit(key, value, indent="  "):
    """Render one YAML key. Multi-line values become literal blocks."""
    if "\n" in value:
        body = "\n".join(indent + "  " + line if line else "" for line in value.split("\n"))
        return "%s%s: |-\n%s" % (indent, key, body)
    return '%s%s: "%s"' % (indent, key, value.replace("\\", "\\\\").replace('"', '\\"'))


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)

    out = [HEADER]
    people = read_rows(sys.argv[1])
    for person in people:
        entry = []
        for key, column in FIELDS:
            value = clean(person.get(column))
            if value:
                entry.append(emit(key, value))
        link = clean(person.get("L"))
        if link:
            entry.append(emit("link_label", link_label(link)))
        # entries are indented two spaces; the first one carries the "- " marker
        out.append("- " + "\n".join(entry)[2:])

    text = "\n\n".join(out) + "\n"
    with open("_data/people.yml", "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote _data/people.yml (%d members)" % len(people))


if __name__ == "__main__":
    main()
