#!/usr/bin/env python3
"""Convert the members' survey export (.xlsx) into _data/people.yml.

The Google Form export is the upstream source of truth; _data/people.yml is
what the site actually renders, sorted 가나다순. Re-run this after a new export
and read the diff before committing.

    python3 tools/import_people.py ~/Downloads/<survey export>.xlsx

Expected columns (Google Forms question order):
    A timestamp   B name(ko)    C name(en)   D affiliation(ko) E affiliation(en)
    F field(ko)   G field(en)   H email      I photo(drive)    J bio(ko)
    K bio(en)     L link        M past presentation titles

Column I is handled by tools/fetch_photos.py, which writes the separate
_data/people_photos.yml. Column M duplicates what _seminar/ already records,
so it is skipped.

Hand edits to this file are overwritten, with one exception: paragraph breaks
added to bios by tools/paragraph_bios.py are kept, since bios are compared
with whitespace removed and the form has no way to express them.
"""

import os
import re
import sys
import zipfile
from xml.etree import ElementTree as ET

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
M = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"

FIELDS = [
    ("name", "B"),
    ("name_en", "C"),
    ("affiliation", "D"),
    ("affiliation_en", "E"),
    ("field", "F"),
    ("field_en", "G"),
    ("email", "H"),
    ("bio", "J"),
    ("bio_en", "K"),
    ("link", "L"),
]

# Personal links show as a platform name rather than a raw URL. Anything not
# recognised falls back to its bare domain, which reads the same in KO and EN.
PLATFORMS = [
    ("linkedin.com", "LinkedIn"),
    ("notion.site", "Notion"),
    ("notion.so", "Notion"),
    ("github.com", "GitHub"),
    ("instagram.com", "Instagram"),
    ("x.com", "X"),
    ("twitter.com", "X"),
    ("orcid.org", "ORCID"),
    ("scholar.google", "Google Scholar"),
    ("academia.edu", "Academia.edu"),
    ("researchgate.net", "ResearchGate"),
    ("brunch.co.kr", "brunch"),
    ("tistory.com", "Tistory"),
    ("velog.io", "velog"),
]


def link_label(url):
    """A human label for a personal link: platform name, else the bare domain."""
    host = re.sub(r"^https?://", "", url).split("/")[0].lower()
    for needle, label in PLATFORMS:
        if needle in host:
            return label
    return re.sub(r"^www\.", "", host)

OUT_PATH = "_data/people.yml"

HEADER = """# Members, generated by tools/import_people.py from the survey export.
# Rendered by people.html. Re-run the importer rather than editing by hand.
"""


def read_rows(path):
    """Return the sheet as a list of {column letter: value} dicts, minus the header."""
    z = zipfile.ZipFile(path)
    shared = [
        "".join(t.text or "" for t in si.iter(M + "t"))
        for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall("m:si", NS)
    ]

    rows = {}
    for row in ET.fromstring(z.read("xl/worksheets/sheet1.xml")).iter(M + "row"):
        cells = {}
        for c in row.findall("m:c", NS):
            v = c.find("m:v", NS)
            if v is None or v.text is None:
                continue
            value = shared[int(v.text)] if c.get("t") == "s" else v.text
            cells[re.sub(r"\d+$", "", c.get("r"))] = value
        rows[int(row.get("r"))] = cells

    return [rows[i] for i in sorted(rows) if i >= 2]


def title_case(name):
    """Normalise a romanised name to Title Case.

    People typed these however they liked -- "CHANHEE LEE", "yu mireu",
    "EOM Yoon ju" -- and the mix looks like inconsistency rather than
    intent. The trailing comma in a surname-first entry ("Ahn, Jinho") goes
    too, so every name reads as plain words.
    """
    words = name.replace(",", " ").split()
    return " ".join(w[:1].upper() + w[1:].lower() for w in words)


# Answers that need a correction the form cannot make on its own. Kept here,
# and applied on every run, so a re-import does not quietly undo them.
OVERRIDES = {
    # Put the research interests in the bio field, not the one-line 전공 slot,
    # where they render as "Seoul National University · Art History | Research
    # interests: ..." beside everyone else's plain department name.
    ("김지현", "field_en"): "Art History",
}

MINOR_WORDS = {"of", "and", "the", "for", "in", "on", "at", "to"}


def sentence_case(text):
    """Fix answers typed in all caps, leaving acronyms alone.

    "SEOUL NATIONAL UNIVERSITY" is shouting; "KAIST CT" and "LMU Munich" are
    how those names are actually written. The test is whether the string has
    any lowercase at all and whether it contains a word too long to be an
    acronym -- five letters or fewer stays untouched.
    """
    if any(c.islower() for c in text):
        return text
    if not any(len(w.strip(",.&")) >= 6 for w in text.split()):
        return text

    words = []
    for i, word in enumerate(text.split()):
        lowered = word.lower()
        if i and lowered.strip(",") in MINOR_WORDS:
            words.append(lowered)
        else:
            words.append(lowered[:1].upper() + lowered[1:])
    return " ".join(words)


def clean(value):
    """Normalise a cell: strip stray whitespace, drop zero-width junk from pasted text."""
    if not value:
        return ""
    value = value.replace("\r\n", "\n").replace("​", "").replace("\xa0", " ")
    return "\n".join(line.strip() for line in value.split("\n")).strip("\n ")


ENTRY_RE = re.compile(r"^(- |  )(\w+): (.*)$")


def read_existing(path):
    """Parse a people.yml this script wrote earlier, keyed by Korean name.

    Only handles the subset of YAML emit() produces -- quoted scalars and
    literal blocks -- which is enough, since nothing else writes this file.
    """
    if not os.path.exists(path):
        return {}

    lines = open(path, encoding="utf-8").read().split("\n")
    entries, cur, i = [], None, 0
    while i < len(lines):
        m = ENTRY_RE.match(lines[i])
        if not m:
            i += 1
            continue

        marker, key, value = m.groups()
        if marker == "- ":
            cur = {}
            entries.append(cur)
        if cur is None:
            i += 1
            continue

        if value == "|-":
            block, i = [], i + 1
            while i < len(lines):
                line = lines[i]
                if line.startswith("    "):
                    block.append(line[4:])
                elif line == "" and i + 1 < len(lines) and lines[i + 1].startswith("    "):
                    block.append("")  # blank line inside the block, not the end of it
                else:
                    break
                i += 1
            cur[key] = "\n".join(block).rstrip()
            continue

        cur[key] = value.strip('"').replace('\\"', '"').replace("\\\\", "\\")
        i += 1

    return {e["name"]: e for e in entries if e.get("name")}


def squash(text):
    """Text with all whitespace removed, for comparing wording independently
    of how it happens to be broken into lines and paragraphs."""
    return re.sub(r"\s+", "", text or "")


def emit(key, value, indent="  "):
    """Render one YAML key. Multi-line values become literal blocks."""
    if "\n" in value:
        body = "\n".join(indent + "  " + line if line else "" for line in value.split("\n"))
        return "%s%s: |-\n%s" % (indent, key, body)
    return '%s%s: "%s"' % (indent, key, value.replace("\\", "\\\\").replace('"', '\\"'))


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)

    out = [HEADER]
    # 가나다순. Precomposed Hangul syllables sit in 가나다 order in Unicode, so a
    # plain codepoint sort is the right collation here; sorting the file itself
    # rather than the template keeps diffs stable across re-imports, since the
    # export arrives in whatever order people happened to answer the form.
    people = sorted(read_rows(sys.argv[1]), key=lambda row: clean(row.get("B")))
    existing = read_existing(OUT_PATH)
    kept = 0

    for person in people:
        entry = []
        prior = existing.get(clean(person.get("B")), {})
        for key, column in FIELDS:
            value = clean(person.get(column))
            value = OVERRIDES.get((clean(person.get("B")), key), value)
            if key == "name_en":
                value = title_case(value)
            elif key in ("affiliation_en", "field_en"):
                value = sentence_case(value)
            # Long bios are broken into paragraphs by hand for readability.
            # That editing is invisible to the form, so a re-import would undo
            # it; keep the edited text whenever the wording itself is unchanged.
            if key in ("bio", "bio_en") and squash(prior.get(key)) == squash(value) != "":
                if prior[key] != value:
                    kept += 1
                value = prior[key]
            if value:
                entry.append(emit(key, value))
        link = clean(person.get("L"))
        if link:
            entry.append(emit("link_label", link_label(link)))
        # entries are indented two spaces; the first one carries the "- " marker
        out.append("- " + "\n".join(entry)[2:])

    text = "\n\n".join(out) + "\n"
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %s (%d members)" % (OUT_PATH, len(people)))
    if kept:
        print("kept hand-edited paragraphing on %d bio field(s)" % kept)


if __name__ == "__main__":
    main()
